<a href="https://colab.research.google.com/github/Varunboppishetty/project/blob/main/datascience%20project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### New Secton

# **MILEAGE PREDICTION-REGRESSION ANALYSIS**

**source**:
This dataset was taken from the Statlib library which is maintained at the carnegie mellon University

**Data Set information:**
This dataset is a slightly modified version of the dataset provided in the Statlib library.in line with the use by Ross Quninlan in predicting the attribute "mpg".The original dataset is available in the file "auto-mpg.original".

**Attribute information:**

mpg:continuos
cylinders:multivalued discrete
displacement:continuous
horsepower:continuous
weight:continuous
acceleration:continuous

In [30]:
import pandas as pd

In [31]:
import numpy as np

In [32]:
import matplotlib.pyplot as plt

In [33]:
import seaborn as sns

In [34]:
df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/MPG.csv')

In [35]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [36]:
df.nunique()

mpg             129
cylinders         5
displacement     82
horsepower       93
weight          351
acceleration     95
model_year       13
origin            3
name            305
dtype: int64

# **Data Prepocessing**

In [37]:
df = df.dropna()

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64  
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64  
 7   origin        392 non-null    object 
 8   name          392 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 30.6+ KB


In [39]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  392.000000  392.000000    392.000000  392.000000   392.000000   
mean    23.445918    5.471939    194.411990  104.469388  2977.584184   
std      7.805007    1.705783    104.644004   38.491160   849.402560   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.000000    4.000000    105.000000   75.000000  2225.250000   
50%     22.750000    4.000000    151.000000   93.500000  2803.500000   
75%     29.000000    8.000000    275.750000  126.000000  3614.750000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    392.000000  392.000000  
mean      15.541327   75.979592  
std        2.758864    3.683737  
min        8.000000   70.000000  
25%       13.775000   73.000000  
50%       15.500000   76.000000  
75%       17.025000   79.000000  
max       24.800000   82.000000

In [40]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [41]:
X = df[['displacement','horsepower','weight','acceleration']]

In [42]:
y = df['mpg']

# **Train Test Split Data**

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.7,random_state=2529)

In [45]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((117, 4), (275, 4), (117,), (275,))

# **Linear Regression model**

In [46]:
from sklearn.linear_model import LinearRegression

In [47]:
lr = LinearRegression()

In [49]:
lr.fit(X_train , y_train)

LinearRegression()

In [50]:
lr.intercept_

44.00934827526879

In [51]:
lr.coef_

array([-0.01024643, -0.01668317, -0.00610645,  0.09710601])

array([-0.01024643, -0.01668317, -0.00610645,  0.09710601])

# **Predict test data**

In [53]:
y_pred = lr.predict(X_test)

In [54]:
y_pred

array([18.83232615, 14.67689764, 13.90916105, 23.48706843, 30.25543552,
       23.46671071, 27.28163576, 24.60121655, 14.40764431, 10.81692289,
       24.30874146, 27.9134718 , 31.87135668, 31.42289874, 17.69562279,
       19.09989244, 28.60563403, 32.67685665, 31.45063299, 27.35959705,
       18.46314382, 22.19920123, 26.2982957 , 33.03335117, 20.48801313,
        9.54351607, 22.40016431, 18.3349025 , 24.90567933, 17.72005616,
       23.00135022, 16.88953804, 10.57530881, 30.26775706, 20.13255834,
       29.29639211, 24.89285218, 21.37238187,  9.68643504, 12.73666785,
       20.95618571, 20.11237202,  6.42862798, 17.31748152, 22.17367358,
       29.47288305, 13.72946495, 25.84603835, 30.3260242 , 22.49617884,
       21.32125793, 16.21218023, 23.82532354, 30.39683971,  9.25868474,
       10.87274956, 28.51433586, 23.14656115, 20.00708585, 31.00621369,
       20.4572209 , 27.13086597, 22.2195037 , 13.80505274, 25.30799492,
       27.41913866, 15.02111221, 24.0510285 , 31.58339665, 14.71

# **Model Accuracy**

In [55]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [59]:
mean_absolute_error(y_test,y_pred)

3.3564087099398763